//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nAsterisk.AGI.ScriptHost.AddInSideAdapters
{
    
    public class IRemoteScriptManagerAddInAdapter
    {
        internal static nAsterisk.AGI.ScriptHost.IRemoteScriptManager ContractToViewAdapter(nAsterisk.AGI.ScriptHost.Contract.IRemoteScriptManagerContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IRemoteScriptManagerViewToContractAddInAdapter))))
            {
                return ((IRemoteScriptManagerViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IRemoteScriptManagerContractToViewAddInAdapter(contract);
            }
        }
        internal static nAsterisk.AGI.ScriptHost.Contract.IRemoteScriptManagerContract ViewToContractAdapter(nAsterisk.AGI.ScriptHost.IRemoteScriptManager view)
        {
            if (view.GetType().Equals(typeof(IRemoteScriptManagerContractToViewAddInAdapter)))
            {
                return ((IRemoteScriptManagerContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IRemoteScriptManagerViewToContractAddInAdapter(view);
            }
        }
    }
}

