//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nAsterisk.AGI.ScriptHost.HostSideAdapters
{
    
    public class IRemoteScriptManagerHostAdapter
    {
        internal static nAsterisk.AGI.ScriptHost.IRemoteScriptManager ContractToViewAdapter(nAsterisk.AGI.ScriptHost.Contract.IRemoteScriptManagerContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IRemoteScriptManagerViewToContractHostAdapter))))
            {
                return ((IRemoteScriptManagerViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IRemoteScriptManagerContractToViewHostAdapter(contract);
            }
        }
        internal static nAsterisk.AGI.ScriptHost.Contract.IRemoteScriptManagerContract ViewToContractAdapter(nAsterisk.AGI.ScriptHost.IRemoteScriptManager view)
        {
            if (view.GetType().Equals(typeof(IRemoteScriptManagerContractToViewHostAdapter)))
            {
                return ((IRemoteScriptManagerContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IRemoteScriptManagerViewToContractHostAdapter(view);
            }
        }
    }
}

