//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nAsterisk.AGI.ScriptHost.HostSideAdapters
{
    
    public class IRemoteScriptManagerViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, nAsterisk.AGI.ScriptHost.Contract.IRemoteScriptManagerContract
    {
        private nAsterisk.AGI.ScriptHost.IRemoteScriptManager _view;
        public IRemoteScriptManagerViewToContractHostAdapter(nAsterisk.AGI.ScriptHost.IRemoteScriptManager view)
        {
            _view = view;
        }
        public virtual void Execute(nAsterisk.AGI.ScriptHost.Contract.IAGIScriptHostContract host, System.Collections.Generic.Dictionary<string, string> configurationSettings)
        {
            _view.Execute(nAsterisk.AGI.ScriptHost.HostSideAdapters.IAGIScriptHostHostAdapter.ContractToViewAdapter(host), configurationSettings);
        }
        internal nAsterisk.AGI.ScriptHost.IRemoteScriptManager GetSourceView()
        {
            return _view;
        }
    }
}

