//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nAsterisk.AGI.ScriptHost
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IRemoteScriptManager
    {
        void Execute(IAGIScriptHost host, System.Collections.Generic.Dictionary<string, string> configurationSettings);
    }
}

